import { ConsoleLogger } from '@nestjs/common';
import { spawn } from 'child_process';
import net from 'net';
import { BrowserContext, Page } from '@playwright/test';
import { BigNumber, Contract, providers, utils } from 'ethers';
import {
  Account,
  ERC20_SHORT_ABI,
  EthereumNodeServiceOptions,
} from './node.constants';
import { RpcProxyService } from './rpc.proxy.service';
import {
  ANVIL_DEFAULT_DERIVATION_PATH,
  ANVIL_DEFAULT_PORT,
  ANVIL_FATAL_PATTERNS,
  ANVIL_IMPERSONATE_ETH_BALANCE,
  ANVIL_LOG_DIR,
  ANVIL_RESTART_PATTERNS,
} from './anvil.constants';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import fs, { WriteStream } from 'node:fs';

const logger = new ConsoleLogger('EthereumNodeService');

export class EthereumNodeService {
  private provider: any;
  /** File stream for full Anvil output (stdout + stderr). Active only when forkLog.logToFile is enabled.
   *  Console receives only the first line of each chunk (truncated); the file gets the full raw output.
   *  Closed explicitly in stopNode() to avoid data loss on flush. */
  private logStream?: WriteStream;
  /** Rolling buffer of the last 20 stderr lines from Anvil. Used by diagnoseStderr() to detect
   *  fatal errors (throw) and transient errors (restart) when the process exits or gets stuck. */
  private lastAnvilStderr: string[] = [];
  private readonly privateKeys: string[] = [];
  private readonly host = '127.0.0.1';
  private readonly localForkConfigPath = 'local_fork_config.json';
  private readonly rpcProxy: RpcProxyService;

  private get port(): number {
    return this.options.port ?? ANVIL_DEFAULT_PORT;
  }
  private get defaultBalance(): number {
    return this.options.defaultBalance ?? 100;
  }
  private get accountsLength(): number {
    return this.options.accountsLength ?? 30;
  }
  private get blockTime(): number {
    return this.options.blockTime ?? 2;
  }
  private get derivationPath(): string {
    return this.options.derivationPath ?? ANVIL_DEFAULT_DERIVATION_PATH;
  }
  private get runOptions(): string[] {
    return this.options.runOptions ?? [];
  }

  state?: {
    nodeProcess: ReturnType<typeof spawn | typeof undefined>;
    nodeUrl: string;
    accounts: Account[];
  };

  constructor(private options: EthereumNodeServiceOptions) {
    this.rpcProxy = new RpcProxyService(
      options.mockConfig.rpcUrlToMock,
      () => this.state?.nodeUrl || this.options.rpcUrl,
    );
  }

  // extended usage only
  public getProvider(): providers.JsonRpcProvider {
    return this.provider;
  }

  /**
   * Reads private keys from the Anvil config file written by --config-out.
   * Called automatically by startNode() after the node is ready.
   * The file is generated by Anvil at startup and contains the accounts
   * and their private keys for the current session.
   */
  loadDataFromConfig() {
    try {
      const configPath = path.resolve(process.cwd(), this.localForkConfigPath);
      if (!fs.existsSync(configPath)) {
        throw new Error(
          `${this.localForkConfigPath} not found at ${configPath}`,
        );
      }
      const raw = fs.readFileSync(configPath, 'utf8');
      const json = JSON.parse(raw);
      if (Array.isArray(json?.private_keys)) {
        this.privateKeys.push(...json.private_keys);
      } else {
        logger.warn(`private_keys not found in ${this.localForkConfigPath}`);
      }
      return this.privateKeys;
    } catch (e) {
      throw new Error(
        // @ts-expect-error e message
        `Failed to read ${this.localForkConfigPath}: ${e.message}`,
      );
    }
  }

  /**
   * Spawns the Anvil process and wires up stdout/stderr listeners.
   *
   * stdout — consumed unconditionally to prevent the pipe buffer from blocking
   *          the process on some platforms; forwarded to console/file if forkLog is enabled.
   *
   * stderr — stored in a rolling 20-line buffer (lastAnvilStderr) for pattern
   *          diagnosis. Only the first line of each chunk is logged to the console
   *          (truncated to 200 chars) to avoid flooding the terminal with multi-KB
   *          HTML error pages that upstream RPCs sometimes return.
   *          Full output is always written to the log file when logToFile is enabled.
   *
   * The process itself is returned immediately — readiness is checked separately
   * in waitForAnvilReady().
   */
  private startAnvil() {
    const args = [
      `--host=${this.host}`,
      `--fork-url=${this.options.rpcUrl}`,
      `--port=${this.port}`,
      `--balance=${this.defaultBalance}`,
      `--block-time=${this.blockTime}`,
      `--accounts=${this.accountsLength}`,
      `--derivation-path=${this.derivationPath}`,
      `--config-out=${this.localForkConfigPath}`,
      ...this.runOptions,
    ];

    const anvilProcess = spawn('anvil', args, { stdio: 'pipe' });

    if (this.options.forkLog?.enabled && this.options.forkLog?.logToFile) {
      fs.mkdirSync(ANVIL_LOG_DIR, { recursive: true });

      const stamp = new Date().toISOString().replace(/[:.]/g, '-');
      const fileName = `anvil-log-${stamp}.log`;
      const filePath = path.join(ANVIL_LOG_DIR, fileName);
      this.logStream = fs.createWriteStream(filePath, { flags: 'w' });
    }

    // DONT REMOVE THIS: prevents process from hanging on some platforms
    anvilProcess.stdout.on('data', (data) => {
      if (!this.options.forkLog?.enabled) return;
      if (this.options.forkLog?.logToConsole) {
        logger.debug(`[Anvil logs] ${data}`);
      }
      if (this.logStream) {
        this.logStream.write(
          `[${new Date().toISOString()}] ${data.toString()}`,
        );
      }
    });

    this.lastAnvilStderr = [];
    anvilProcess.stderr.on('data', (data) => {
      const line = data.toString();
      this.lastAnvilStderr.push(line);
      if (this.lastAnvilStderr.length > 20) this.lastAnvilStderr.shift();
      const firstLine = line.split('\n')[0].trim();
      const truncatedLog =
        firstLine.length > 200 ? `${firstLine.slice(0, 200)}…` : firstLine;
      logger.debug(`[Anvil STDERR] ${truncatedLog}`);
      if (this.logStream)
        this.logStream.write(`[${new Date().toISOString()}] ${line}`);
    });

    anvilProcess.on('close', (code) => {
      if (code === 0) logger.log(`[Anvil] Process exited cleanly`);
      else logger.warn(`[Anvil] Process exited with code ${code}`);

      if (this.logStream)
        this.logStream.write(
          `[${new Date().toISOString()}] Anvil Closed with code ${code}`,
        );
    });

    return anvilProcess;
  }

  /**
   * Starts the Ethereum node and initialises the service state.
   * Idempotent — does nothing if the node is already running.
   *
   * If useExternalFork is false (default): spawns a local Anvil process,
   * waits for it to become ready, and enables auto-restart on transient failures.
   * If useExternalFork is true: skips Anvil entirely and connects directly
   * to the RPC URL (useful for CI environments with a shared fork).
   *
   * After the node is ready: loads account private keys from the Anvil config file,
   * builds the accounts list, and runs warmUpCallback if provided.
   */
  async startNode() {
    if (this.state) return;
    const nodeUrl = `http://${this.host}:${this.port}`;
    let anvilProcess;

    if (!this.options.useExternalFork) {
      const rpcUrl = this.options.rpcUrl;
      if (!rpcUrl) throw new Error('RPC URL is required');

      logger.log('Starting local Anvil node...');
      anvilProcess = this.startAnvil();

      await this.waitForAnvilReady(nodeUrl, anvilProcess, {
        restartFn: () => {
          anvilProcess = this.startAnvil();
          return anvilProcess;
        },
      });
    }
    logger.log(`Ethereum node is running at ${nodeUrl}`);

    // Load private keys after node is ready
    this.loadDataFromConfig();

    this.provider = new providers.JsonRpcProvider(nodeUrl);
    const addresses = await this.provider.listAccounts();
    const accounts: Account[] = addresses.map((address, index) => ({
      address,
      secretKey: this.privateKeys?.[index] || '',
    }));

    if (this.options.warmUpCallback) {
      logger.debug('Running warm-up callback...');
      await this.options.warmUpCallback();
      logger.debug('Warm-up callback completed.');
    }

    this.state = { nodeProcess: anvilProcess, nodeUrl, accounts };
  }

  /**
   * Sets the default ERC-20 token balances for the first account (index 0)
   * for each token defined in options.tokens.
   * Fails fast — if any token setup throws, the error is logged and re-thrown
   * so the caller knows the node is not fully initialised.
   */
  async setupDefaultTokenBalances() {
    if (this.options.tokens) {
      const wallet = this.getAccount();
      logger.log(`Setup balance for ${wallet.address}:`);
      for (const token of this.options.tokens) {
        logger.log(`+ ${this.defaultBalance} ${token.name}`);
        try {
          await this.setErc20Balance(
            wallet,
            token.address,
            token.mappingSlot,
            this.defaultBalance,
          );
        } catch (e) {
          logger.error(
            `Failed to set balance for token ${token.name} (${
              token.address
            }): ${e instanceof Error ? e.message : e}`,
          );
          throw e;
        }
      }
    }
  }

  getAccount(index = 0): Account {
    return this.state?.accounts[index];
  }

  async getBalance(account: Account): Promise<string | undefined> {
    if (!this.state) return undefined;
    const balance = await this.provider.getBalance(account.address);
    return utils.formatEther(balance);
  }

  /**
   * Sets the ERC-20 token balance for an account by directly writing to contract storage.
   * Returns the new balance in token units (not wei).
   */
  async setErc20Balance(
    account: Account,
    tokenAddress: string,
    mappingSlot: any,
    balance: number, // ether value
  ): Promise<BigNumber> {
    if (!this.state) throw new Error('Node not ready');
    const contract = new Contract(tokenAddress, ERC20_SHORT_ABI, this.provider);
    const decimals = BigNumber.from(10).pow(await contract.decimals());
    const mappingSlotHex = BigNumber.from(mappingSlot).toHexString();

    const slot = utils.solidityKeccak256(
      ['bytes32', 'bytes32'],
      [
        utils.hexZeroPad(account.address, 32),
        utils.hexZeroPad(mappingSlotHex, 32),
      ],
    );

    const value = BigNumber.from(balance).mul(decimals);

    await this.provider.send('anvil_setStorageAt', [
      tokenAddress,
      slot,
      utils.hexZeroPad(value.toHexString(), 32),
    ]);

    const balanceAfter = await contract.balanceOf(account.address);
    return balanceAfter.div(decimals);
  }

  /**
   * Sets the ERC-20 token balance by impersonating the token's controller and calling generateTokens().
   * Use this for tokens where direct storage manipulation (setErc20Balance) doesn't work.
   */
  async setErc20BalanceImpersonate(
    tokenAbi: any[],
    tokenAddress: string,
    account: Account,
    amount: number, // ether value
  ): Promise<string> {
    const erc20Token = new Contract(tokenAddress, tokenAbi, this.provider);

    // decimals & amount -> wei
    const decimals: number = await erc20Token.decimals();
    const amountWei = utils.parseUnits(amount.toString(), decimals);

    const controllerAddress: string = await erc20Token.controller();

    // impersonate + gas
    await this.provider.send('anvil_impersonateAccount', [controllerAddress]);
    await this.provider.send('anvil_setBalance', [
      controllerAddress,
      ANVIL_IMPERSONATE_ETH_BALANCE,
    ]);

    const ctrlSigner = this.provider.getSigner(controllerAddress);
    const tokenAsCtrl = erc20Token.connect(ctrlSigner);

    // enable transfers if possible & disabled
    try {
      const enabled: boolean = await tokenAsCtrl.transfersEnabled();
      if (!enabled) {
        const tx = await tokenAsCtrl.enableTransfers(true);
        await tx.wait();
      }
    } catch {
      // if no transfersEnabled/enableTransfers - just skip
    }

    // mint impersonated erc20 token
    const tx = await tokenAsCtrl.generateTokens(account.address, amountWei);
    await tx.wait();

    const balanceAfter = await erc20Token.balanceOf(account.address);
    return balanceAfter.div(decimals);
  }

  /**
   * Polls until the Anvil node is ready to accept RPC requests, with automatic
   * restart support for transient failures.
   *
   * Flow per iteration:
   *  1. exitCode check — if the process has already exited, diagnose stderr:
   *       • fatal pattern (e.g. invalid URL, port in use) → throw immediately.
   *       • any other exit → restart via restartFn if provided, otherwise throw.
   *  2. TCP port check — skip the HTTP request entirely while the port is not
   *     yet bound; this avoids ECONNREFUSED noise in the logs.
   *  3. Stuck detection — every logIntervalMs, if the port is still not open,
   *     check stderr for restart patterns (rate limit, timeout, etc.) and
   *     restart the process preemptively.
   *  4. HTTP health-check — send eth_blockNumber; return true on a valid result.
   *
   * Throws if the node does not become ready within timeoutMs.
   */
  private async waitForAnvilReady(
    rpcUrl: string,
    anvilProcess?: ReturnType<typeof spawn>,
    {
      timeoutMs = 60000,
      delayMs = 500,
      logIntervalMs = 5000,
      restartFn,
    }: {
      timeoutMs?: number;
      delayMs?: number;
      logIntervalMs?: number;
      restartFn?: () => ReturnType<typeof spawn>;
    } = {},
  ): Promise<boolean> {
    const start = Date.now();
    let lastLogAt = 0;

    while (Date.now() - start < timeoutMs) {
      // 1. Process exited — diagnose stderr and decide: fatal throw or restart
      if (anvilProcess?.exitCode !== null) {
        const diagnosis = this.diagnoseStderr();
        if (diagnosis?.type === 'fatal') {
          throw new Error(
            `Anvil fatal error: ${
              diagnosis.reason
            }\n${this.lastAnvilStderr.join('')}`,
          );
        }
        if (restartFn) {
          logger.warn(
            `Anvil process exited with code ${anvilProcess.exitCode}${
              diagnosis ? `: ${diagnosis.reason}` : ''
            }. Restarting...`,
          );
          anvilProcess = restartFn();
          await this.sleep(delayMs);
          continue;
        }
        throw new Error(
          `Anvil process exited unexpectedly with code ${anvilProcess.exitCode}`,
        );
      }

      // 2. TCP check — skip HTTP until the port is actually bound
      const { port } = new URL(rpcUrl);
      const portOpen = !(await this.ensurePortAvailable(Number(port)));

      // 3. Throttled logging + stuck detection via stderr patterns
      const now = Date.now();
      if (now - lastLogAt >= logIntervalMs) {
        logger.debug(
          portOpen
            ? `Port is open, sending eth_blockNumber...`
            : `Waiting for Anvil to bind port ${port}...`,
        );
        lastLogAt = now;

        // If port is still not bound after logIntervalMs — check stderr for stuck patterns
        if (!portOpen && restartFn) {
          const diagnosis = this.diagnoseStderr();
          if (diagnosis?.type === 'restart') {
            logger.warn(`Anvil is stuck: ${diagnosis.reason}. Restarting...`);
            anvilProcess.kill('SIGKILL');
            anvilProcess = restartFn();
          }
        }
      }

      if (!portOpen) {
        await this.sleep(delayMs);
        continue;
      }

      // 4. HTTP health-check — node is ready when eth_blockNumber returns a result
      try {
        const res = await fetch(rpcUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            jsonrpc: '2.0',
            method: 'eth_blockNumber',
            params: [],
            id: 1,
          }),
          signal: AbortSignal.timeout(5000),
        });

        const resBody = await res.json();
        const isHealthy = !resBody.error && !!resBody.result;

        if (isHealthy) return isHealthy;
      } catch (error: any) {
        logger.debug(`RPC not ready: ${error?.message || 'Unknown error'}`);
      }

      await this.sleep(delayMs);
    }

    throw new Error(`Fork did not become ready within ${timeoutMs} ms`);
  }

  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  private diagnoseStderr(): {
    type: 'fatal' | 'restart';
    reason: string;
  } | null {
    const stderr = this.lastAnvilStderr.join('');
    const fatal = ANVIL_FATAL_PATTERNS.find(({ pattern }) =>
      pattern.test(stderr),
    );
    if (fatal) return { type: 'fatal', reason: fatal.reason };
    const restart = ANVIL_RESTART_PATTERNS.find(({ pattern }) =>
      pattern.test(stderr),
    );
    if (restart) return { type: 'restart', reason: restart.reason };
    return null;
  }

  private ensurePortAvailable(port: number): Promise<boolean> {
    return new Promise((resolve) => {
      const socket = new net.Socket();
      socket.once('error', () => resolve(true));
      socket.once('connect', () => {
        socket.destroy();
        resolve(false);
      });
      socket.connect(port, this.host);
    });
  }

  /**
   * Intercepts browser RPC requests and proxies them to the local Anvil node.
   * Allows tests to use a real wallet UI while all blockchain calls go to the fork.
   */
  async mockRoute(contextOrPage: BrowserContext | Page): Promise<void> {
    if (!this.options.mockConfig.mockEnabled) return;
    await this.rpcProxy.mockRoute(contextOrPage);
  }

  /** Gracefully stops the Anvil process (SIGTERM → SIGKILL after 5s), waits for the port to be released, and closes the log stream. */
  async stopNode(): Promise<void> {
    if (this.options.useExternalFork) {
      logger.log('Using external fork. Skipping node stop.');
      return;
    }
    if (this.state) {
      logger.log('Stopping Node...');
      const nodeProcess = this.state.nodeProcess;

      const processExited = new Promise<void>((resolve, reject) => {
        nodeProcess.once('exit', resolve);
        nodeProcess.once('close', resolve);
        nodeProcess.once('error', reject);
      });

      nodeProcess.kill('SIGTERM');

      const timeout = new Promise<void>((resolve) =>
        setTimeout(() => {
          nodeProcess.kill('SIGKILL');
          resolve();
        }, 5000),
      );

      await Promise.race([processExited, timeout]);

      // Ensure the port is free
      try {
        await this.waitUntilPortIsFree(this.port);
      } catch (err) {
        logger.warn(
          `Timeout while waiting for port ${this.port} to be released`,
        );
      }

      if (this.logStream) {
        const stream = this.logStream;
        this.logStream = undefined;
        await new Promise<void>((resolve) => stream.end(resolve));
      }

      this.state = undefined;
    }
  }

  async [Symbol.asyncDispose](): Promise<void> {
    await this.stopNode();
  }

  /** Forcefully kills any process occupying the given port. Use before startNode() if the port may be stuck from a previous run. */
  static async forceStopNode(port: number): Promise<void> {
    logger.warn(`Port ${port} used. Killing process...`);
    const pids = execFileSync('lsof', ['-ti', String(port)])
      .toString()
      .trim()
      .split('\n')
      .map(Number)
      .filter(Boolean);

    if (!pids.length) return;

    for (const pid of pids) {
      try {
        process.kill(pid, 'SIGKILL');
      } catch (e) {
        throw new Error(`Failed to kill process ${pid} on port ${port}: ${e}`);
      }
    }
    logger.log(`Successfully killed process on port ${port}`);
  }

  /** Polls until the port is no longer bound. Called after SIGTERM to confirm the process has fully released the port. */
  private async waitUntilPortIsFree(
    port: number,
    timeoutMs = 20000,
  ): Promise<void> {
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
      const available = await this.ensurePortAvailable(port);
      if (available) return;
      await this.sleep(100);
    }
    throw new Error(
      `Port ${port} did not become available within ${timeoutMs}ms`,
    );
  }
}
