name: Alpha publish

on:
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install root dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run lint
        run: yarn lint

      - name: Setup NPM token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          ls -la
          cd packages/wallets
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          cat .npmrc
          echo $NPM_TOKEN
          yarn publish --non-interactive
